[package]
name = "micrograd-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
colored = "2.1.0"
csv = "1.3.0"
plotters = "0.3.7"
rand = "0.8.5"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
