[package]
name = "micrograd-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
colored = "2.1.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
